language: ruby

before_install:
  - gem update --system
  - gem install bundler

after_success:
  - git status
  - git conifg --local user.name $GH_USER_NAME
  - git conifg --local user.email $GH_USER_EMAIL
  - git add docs/
  - git commit -m 'Update by Travis CI'
#  - git push https://$GH_USER_NAME:$GH_TOKEN@$GH_REF HEAD:master