language: ruby

before_install:
  - gem update --system
  - gem install bundler

after_success:
  - git conifg --local user.name $GH_USER_NAME
  - git conifg --local user.email $GH_USER_EMAIL
  - cd docs/
  - git init
  - git add .
  - git commit -m "Publishing site on `date "+%Y-%m-%d %H:%M:%S"`"
  - git push -f https://$GH_USER_NAME:$GH_TOKEN@$GH_REF master:gh-pages
